USE sakila;

SELECT CONCAT(UPPER(FIRST_NAME),' ',UPPER(LAST_NAME)) AS FULLNAME
FROM ACTOR;

SELECT ACTOR_ID, FIRST_NAME,LAST_NAME
FROM ACTOR 
WHERE FIRST_NAME ="JOE";

SELECT ACTOR_ID, FIRST_NAME,LAST_NAME
FROM ACTOR 
WHERE LAST_NAME LIKE'%GEN%';

SELECT ACTOR_ID, FIRST_NAME,LAST_NAME
FROM ACTOR 
WHERE LAST_NAME LIKE'%LI%'
ORDER BY LAST_NAME,FIRST_NAME;

SELECT COUNTRY_ID,COUNTRY
FROM COUNTRY 
WHERE COUNTRY IN('AFGHANISTAN','BANGLADESH','CHINA');

SELECT LAST_NAME,COUNT(*) 
FROM ACTOR 
GROUP BY LAST_NAME;

SELECT * FROM ACTOR
WHERE FIRST_NAME = "GROUCHO" AND LAST_NAME = "WILLIAMS";

UPDATE ACTOR SET FIRST_NAME = "HARPO" 
WHERE FIRST_NAME = "GROUCHO" AND LAST_NAME = "WILLIAMS";

UPDATE ACTOR SET FIRST_NAME = "GROUCHO" 
WHERE FIRST_NAME = "HARPO" AND LAST_NAME = "WILLIAMS";

SELECT PAYMENT.STAFF_ID,SUM(AMOUNT),FIRST_NAME
FROM PAYMENT
JOIN STAFF
ON PAYMENT.STAFF_ID = STAFF.STAFF_ID
GROUP BY STAFF_ID;

SELECT TITLE,COUNT(ACTOR_ID)  FROM FILM
JOIN FILM_ACTOR 
ON FILM.FILM_ID = FILM_ACTOR.FILM_ID
GROUP BY TITLE;



SELECT TITLE,COUNT(INVENTORY.FILM_ID) FROM FILM
JOIN INVENTORY
ON FILM.FILM_ID = INVENTORY.FILM_ID
WHERE TITLE ="Hunchback Impossible"
GROUP BY TITLE
;

SELECT TITLE FROM FILM 
WHERE (TITLE LIKE'K%' OR TITLE LIKE'Q%')
 AND LANGUAGE_ID = ( SELECT LANGUAGE_ID FROM LANGUAGE
WHERE NAME = "ENGLISH");

SELECT * FROM RENTAL;

SELECT CUSTOMER_ID FROM CUSTOMER 
WHERE FIRST_NAME = "MARY" AND LAST_NAME ="SMITH";

SELECT STAFF_ID FROM STAFF
WHERE FIRST_NAME = "MIKE" AND LAST_NAME ="HILLYER";

SELECT FILM_ID FROM FILM
WHERE TITLE = "Academy Dinosaur";

INSERT INTO RENTAL (RENTAL_DATE,INVENTORY_ID,CUSTOMER_ID,STAFF_ID,LAST_UPDATE)
VALUES (CURRENT_TIMESTAMP,1,1,1,CURRENT_TIMESTAMP);

SELECT * FROM RENTAL
WHERE CUSTOMER_ID =1;

